// Login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const FACEBOOK_LOGIN_COMPLETE = 'LOGIN_SUCCESSFUL';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';

// Superpowers
export const GET_SUPERPOWERS = 'GET_SUPERPOWERS';
export const ADD_SUPERPOWER = 'ADD_SUPERPOWER';
export const REMOVE_SUPERPOWER = 'REMOVE_SUPERPOWER';
export const UPDATE_SUPERPOWER = 'UPDATE_SUPERPOWER';

//Skills
export const FETCH_SKILLS_SUGGESTIONS = 'FETCH_SKILLS_SUGGESTIONS';
export const FOLLOW_SKILLS = 'FOLLOW_SKILLS';
export const SKILLS_FOLLOWED = 'SKILLS_FOLLOWED';

//Profile
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPADTE_PROFILE';

//Recommendations
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';

//Requests
export const SEND_REQUEST = 'SEND_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';

//Conversations
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATION = 'GET_CONVERSATION';
