module.exports = {
    contacts: [
        'OLIVIA',
        'RUBY',
        'EMILY',
        'GRACE',
        'JESSICA',
        'CHLOE',
        'SOPHIE',
        'LILY',
        'AMELIA',
        'EVIE',
        'MIA',
        'ELLA',
        'CHARLOTTE',
        'LUCY',
        'MEGAN',
        'ELLIE',
        'ISABELLE',
        'ISABELLA',
        'HANNAH',
    ],
};
